- credential: null
  description: ''
  image: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
  name: Default execution environment
  natural_key: {name: Default execution environment, type: execution_environment}
  organization: null
  pull: ''
- credential: null
  description: ''
  image: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
  name: Minimal execution environment
  natural_key: {name: Minimal execution environment, type: execution_environment}
  organization: null
  pull: ''
